account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views 
from . import forms

app_name = 'account'

urlpatterns = [
            path("register/", views.register, name="register"),
            path('login/', views.MyLoginView.as_view(),name='login'),
            path('logout/', auth_views.LogoutView.as_view(), name='logout'),
            path('password_change/',
                 views.MyPasswordChangeView.as_view(),
                 name='password_change'),
            path('password_change/done/',
                 auth_views.PasswordChangeDoneView.as_view(), 
                 name='password_change_done'),
            path("password_reset/",
                 views.MyPasswordResetView.as_view(),
                 name="password_reset"),
            path("password_reset/done/",
                 auth_views.PasswordResetDoneView.as_view(),
                 name="password_reset_done"),
            path("reset/<uidb64>/<token>/",
                 views.MyPasswordResetConfirmView.as_view(),
                 name="password_reset_confirm"),
            path("reset/done/",
                 auth_views.PasswordResetCompleteView.as_view(
                     template_name="registration/password_reset_complete.html"
                 ),
                 name="password_reset_complete"),
            path("change_avatar/", views.change_avatar, name="change_avatar"),
            path("profile/<str:name>/",
                 views.profile,
                 name="profile"),
            path("edit/profile/<str:name>/",
                 views.edit_profile, name="edit_profile"),
            path("avatars/", views.get_avatars, name="get_avatars"),
            path("delete_avatar/", views.delete_avatar, name="delete_avatar"),
            path('update/social/', views.update_social, name='update_social'),
            path('follow_unfollow/', views.follow_unfollow, name='follow'),
        ]

gify/urls.py
from django.urls import path

from . import views 

app_name = "gify"

urlpatterns = [
    path("create/", views.post_create, name="create"),
    path("get_comments/", views.retrieve_comments, name="get_comments"),
    path("comment/add/", views.add_comment, name="add_comment"),
    path('like/', views.like_unlike, name='like_unlike'),
    path('wall/', views.wall, name='wall'),
    path("", views.index, name="index"),
]

network/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('gify.urls', namespace="gify")),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, \
                                      PasswordResetForm, SetPasswordForm
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)

from .models import Profile


class MyPasswordResetConfirmForm(SetPasswordForm):
    """
    Form for confirming new password
    """
    error_messages = {
        "password_mismatch": _("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={
            "autocomplete": "new-password",
            "class": "form-control"
        }),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        widget=forms.PasswordInput(attrs={
            "autocomplete": "new-password",
            "class": "form-control"
        }),
        strip=False,
    )


class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={
            "autocomplete": "email",
            "class": "form-control"
        })
    )


class LoginForm(AuthenticationForm):
        username = forms.CharField(
                max_length=254,
                widget=forms.TextInput(attrs={
                    'class': 'form-control',
                })
            )
        password = forms.CharField(
                    label=_('Password'),
                    strip=False,
                    widget=forms.PasswordInput(attrs={'autocomplete': 'off',
                                                      'class': 'form-control'})
                )
        error_messages = {
                'invalid_login': _(
                        'Invalid credentials'
                    ),
                'inactive': _('This account is inactive'),
            }

class ChangePasswordForm(PasswordChangeForm):
        new_password1 = forms.CharField(
                label=_('New password'),
                widget=forms.PasswordInput(attrs={'autocomplete': 'off',
                                                  'class': 'form-control'}),
                strip=False
            )
        new_password2 = forms.CharField(
                label=_('New password confirmation'),
                strip=False,
                widget=forms.PasswordInput(attrs={'autocomplete': 'off',
                                                  'class': 'form-control'})
            )
        old_password = forms.CharField(
                label=_('Old password'),
                strip=False,
                widget=forms.PasswordInput(attrs={'autocomplete': 'off',
                                                  'class': 'form-control'})
            )

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password",
                               widget=forms.PasswordInput(attrs={
                                   "class": "form-control"
                               }))
    password2 = forms.CharField(label="Repeat Password",
                                widget=forms.PasswordInput(attrs={
                                    "class": "form-control"
                                }))
    avatar = forms.ImageField(required=False, widget=forms.FileInput(
        attrs={"class": "form-control-file"}
    ))

    class Meta:
        model = get_user_model()
        fields = ("username", )
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
        }

        help_texts = {
            "username": ""
        }



    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError("Passwords don't match.")
        return password2

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")

        if len(password) < 8:
            msg = "Password is too short. Min. 8 characters."

            self.add_error("password", msg)

class EditUserForm(forms.ModelForm):
    avatar = forms.ImageField(label="Upload new avatar", required=False, widget=forms.FileInput(
        attrs={"class": "form-control-file"}
    ))
    
    class Meta:
        model = Profile
        fields = ("about", 'title')
        widgets = {
            "about": forms.Textarea(attrs={"class": "form-control", "rows": 5}),
            'title': forms.TextInput(attrs={'class': 'form-control'})
        }

account/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, JsonResponse, HttpRequest
from django.contrib.auth import authenticate, login 
from django.contrib.auth.views import (LoginView, PasswordChangeView,
                                        PasswordResetView,
                                        PasswordResetDoneView,
                                        PasswordResetConfirmView)
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.utils.translation import gettext, gettext_lazy as _
from django.utils.decorators import method_decorator
from common.decorators import redirect_if_logged_in
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.core.files import File
from django.db.models import ProtectedError
from django import forms 
from network.settings import STATIC_URL

from easy_thumbnails.files import get_thumbnailer

from .forms import (LoginForm, ChangePasswordForm,
                    UserRegistrationForm,
                    EditUserForm, MyPasswordResetForm, 
                    MyPasswordResetConfirmForm)
from .models import Avatar, Profile
from gify.utils import create_action


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    """
    Custom view for confirming new passwords
    """
    form_class = MyPasswordResetConfirmForm


class MyPasswordResetView(PasswordResetView):
    """
    Custom password reset view to use custom html template 
    and custom password reset form
    """
    template_name = "registration/password_reset_form.html"
    form_class = MyPasswordResetForm


@method_decorator(redirect_if_logged_in, name='dispatch')
class MyLoginView(LoginView):
    """
    Custom Login View, uses LoginForm as its authentication form. 
    Decorated with 'redirect_if_logged_in' to redirect logged in users 
    from common routes such as 'register'
    """
    authentication_form = LoginForm

class MyPasswordChangeView(PasswordChangeView):
    """
    Custom Password Change View, uses ChangePasswordForm as its form class. 
    """
    form_class = ChangePasswordForm


def register(request: HttpRequest) -> HttpResponse:
    """
    View function for handling user registration
    """
    if request.method == "POST":
        user_form = UserRegistrationForm(data=request.POST, files=request.FILES)
        if user_form.is_valid():
            avatar = request.FILES.get("avatar")
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data["password"]
            )
            new_user.save()
            new_user_profile = Profile.objects.create(user=new_user,
                                                      username=new_user.username)
            if avatar:
                Avatar.objects.create(user=new_user_profile, avatar=avatar)
            else:
                Avatar.objects.create(user=new_user_profile)

            return render(request,
                          "account/register_done.html",
                          { "new_user": new_user})
    else:
        user_form = UserRegistrationForm()

    return render(
        request,
        "account/register.html",
        {"user_form": user_form}
    )

@login_required
def profile(request: HttpRequest, name: str) -> HttpResponse:
    """
    View function for displaying user profiles
    """
    user_profile = get_object_or_404(Profile, user__username=name)

    return render(
        request,
        "account/profile-new.html",
        {'section': 'profile', "user_profile": user_profile}
    )

@login_required
def edit_profile(request: HttpRequest, name: str) -> HttpResponse:
    """ 
    Display edit page for current user and save any changes to the profile.
    Only for logged in users
    """
    user_profile = get_object_or_404(Profile, user__username=name)
    avatar_count = user_profile.avatars.count()

    if user_profile != request.user.profile:
        return redirect("gify:index")

    if request.method == "POST":
        form = EditUserForm(request.POST, instance=user_profile)
        avatar = request.FILES.get("avatar", None)
        if form.is_valid():
            edited_profile = form.save()
            if avatar:
                edited_profile.unselect_avatar()
                Avatar.objects.create(user=edited_profile, avatar=avatar)
            return redirect(reverse("account:profile", args=[user_profile.username]))
    else:
        form = EditUserForm(instance=user_profile)

    return render(
        request,
        "account/edit_profile-new.html",
        {
            "section": "edit",
            "user_profile": user_profile,
            "form": form,
            "avatar_count": avatar_count
        }
    )


@login_required
@require_POST
def get_avatars(request: HttpRequest) -> HttpResponse:
    """
    Handle AJAX requests requesting all avatars for the
    single user.
    """
    SKIP_FIRST_AVATAR = 1
    payload = json.loads(request.body)
    profile_id = payload.get("id")
    profile = Profile.objects.get(pk=profile_id)
    avatars = profile.avatars.all()[SKIP_FIRST_AVATAR:]

    response = JsonResponse({
        "status": "ok",
        "avatars": [
            {
                "id": avatar.id,
                "url": avatar.avatar.url
            }
            for avatar in avatars
        ]
    }, safe=False)
    response.status_code = 200
    return response

@login_required
@require_POST
def change_avatar(request: HttpRequest) -> HttpResponse:
    """
    Handle AJAX requests requesting avatar change
    """
    payload = json.loads(request.body)
    avatar_id = payload.get("id", "")

    try:
        avatar = Avatar.objects.get(id=avatar_id)
        request.user.profile.change_avatar(avatar)
    except Avatar.DoesNotExist:
        avatar = None

    if avatar:
        response = JsonResponse({
            "status": "ok",
            "url": avatar.avatar.url
        })
        response.status_code = 200
        return response
    else:
        response = JsonResponse({
            "status": "Error when handling avatar change"
        })
        response.status_code = 500
        return response

@login_required
@require_POST
def delete_avatar(request):
    """
    Handle AJAX requests requesting avatar deletion
    """
    payload = json.loads(request.body)
    avatar_id = payload.get("id", "")

    try:
        avatar = Avatar.objects.get(id=avatar_id)
        user_profile = request.user.profile
        is_current = avatar.selected
    except (Avatar.DoesNotExist, Profile.DoesNotExists):
        avatar = None
        user_profile = None
        is_current = False

    if is_current:
        user_profile.set_default_avatar()
        thumbnailer = get_thumbnailer(avatar.avatar)
        thumbnailer.delete_thumbnails()
        avatar.delete()
        response = JsonResponse({
            "status": "ok",
            "selected": True
        })
        response.status_code = 201
        return response

    if avatar and user_profile:
        try:
            thumbnailer = get_thumbnailer(avatar.avatar)
            thumbnailer.delete_thumbnails()
            avatar.delete()
            return JsonResponse({
                "status": "ok",
            })
        except ProtectedError:
            return JsonResponse({
                "status": "error"
            })
    else:
        response = JsonResponse({
            "status": "Error when handling avatar deletion"
        })
        response.status_code = 500
        return response



@login_required
@require_POST
def update_social(request):
    """
    Handle AJAX requests updating user's social URLs
    """
    profile = request.user.profile
    body = json.loads(request.body)
    if profile.validate_urls(body):
        profile.update_social_urls(body)
        return JsonResponse({'status': 'ok'}, status=201)
    else:
        return JsonResponse({'status': "Error updating social profiles. Check your links..."}, status=422)


@login_required
@require_POST
def follow_unfollow(request):
    """
    Handle follow / unfollow logic. Requests
    sent via AJAX
    """
    body_parsed = json.loads(request.body)
    profile_id_to_follow = body_parsed.get('profile_id', None)
    action = body_parsed.get('action', None)

    profile_to_follow = Profile.objects.get(id=profile_id_to_follow)

    if action and profile_to_follow:
        if action == 'follow':
            request.user.profile.following.add(profile_id_to_follow)
            create_action(request.user.profile,
                          'is following',
                          profile_to_follow)
        elif action == 'unfollow':
            request.user.profile.following.remove(profile_id_to_follow)
        return JsonResponse({'status': 'ok'}, status=200)
    return JsonResponse({'status': f'Error handling "{action}" action'},
                         status=422)

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
		integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
		crossorigin="anonymous" />
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
	<div class="container-fluid" id="container">
	{% block navbar %}
	{% endblock %}
		<div class="modal-post-container" id="modal_container">
			<div class="modal-create-post">
				<h1>Post new video</h1>
				<form id="new-post-form" method="POST" novalidate>
					{% csrf_token %}
					<label for="link_url">Video URL:</label>
					<input class="form-control" type="url" id="link_url" name="link" required
						pattern=".*(you|stream).*">
					<span class="errorurl" aria-live="polite"></span>
					<input type="submit" id="close_modal" value="Add">
				</form>
			</div>
		</div>

		{% block content %}
		{% endblock content %}

	</div>
	<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
		integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
		crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
		integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
		crossorigin="anonymous"></script>
	<script src="{% static 'js/popover.js' %}"></script>
	<script src="{% static 'js/account_main.js' %}"></script>
	<script src="{% static 'js/gify_main.js' %}"></script>
	<script>
		{% block domready %}
		{% endblock %}
	</script>
</body>

</html>

account/templates/navbar.html
{% load thumbnail %}
<nav id="gify-nav" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand d-lg-none" href="/">Gify</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                                                                        aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-between" id="navbarToggle">

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="/">GIFy <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            {% if section == 'index' %}
            <li class="nav-item">
                <a class="nav-link" id="open" href="#">Add</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" id="" href="{% url 'gify:wall' %}">Wall</a>
            </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                {% with avatar=request.user.profile.get_avatar %}
                <a role="button" id="avatar-link" class="nav-link" href="#" data-bs-toggle="popover" tabindex="0">
                    <img id="avatar-nav" src="{{ request.user.profile.get_avatar|thumbnail_url:'avatar' }}" alt="Your avatar">
                </a>
                {% endwith %}
                <div id="popover-profile" style="display: none;">
                    <h6>Welcome {{ user.username }}</h6>
                    {% if section == "index" or section == "edit" %}
                    <a class="btn navButton" href="{% url 'account:profile' user.username %}" role="button">Profile</a>
                    {% else %}
                    <a class="btn navButton" href="{% url 'gify:index' %}" role="button">Dashboard</a>
                    {% endif %}
                    <a class="btn navButton" href="{% url 'account:logout' %}" role="button">Logout</a>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>