account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views 
from . import forms

app_name = 'account'

urlpatterns = [
            path("register/", views.register, name="register"),
            path('login/', views.MyLoginView.as_view(),name='login'),
            path('logout/', auth_views.LogoutView.as_view(), name='logout'),
            path('password_change/',
                 views.MyPasswordChangeView.as_view(),
                 name='password_change'),
            path('password_change/done/',
                 auth_views.PasswordChangeDoneView.as_view(), 
                 name='password_change_done'),
            path("password_reset/",
                 views.MyPasswordResetView.as_view(),
                 name="password_reset"),
            path("password_reset/done/",
                 auth_views.PasswordResetDoneView.as_view(),
                 name="password_reset_done"),
            path("reset/<uidb64>/<token>/",
                 views.MyPasswordResetConfirmView.as_view(),
                 name="password_reset_confirm"),
            path("reset/done/",
                 auth_views.PasswordResetCompleteView.as_view(
                     template_name="registration/password_reset_complete.html"
                 ),
                 name="password_reset_complete"),
            path("change_avatar/", views.change_avatar, name="change_avatar"),
            path("profile/<str:name>/",
                 views.profile,
                 name="profile"),
            path("edit/profile/<str:name>/",
                 views.edit_profile, name="edit_profile"),
            path("avatars/", views.get_avatars, name="get_avatars"),
            path("delete_avatar/", views.delete_avatar, name="delete_avatar"),
            path('update/social/', views.update_social, name='update_social'),
            path('follow_unfollow/', views.follow_unfollow, name='follow'),
        ]

gify/urls.py
from django.urls import path

from . import views 

app_name = "gify"

urlpatterns = [
    path("create/", views.post_create, name="create"),
    path("get_comments/", views.retrieve_comments, name="get_comments"),
    path("comment/add/", views.add_comment, name="add_comment"),
    path('like/', views.like_unlike, name='like_unlike'),
    path('wall/', views.wall, name='wall'),
    path("", views.index, name="index"),
]

network/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('gify.urls', namespace="gify")),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

gify/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from account.models import Profile

from account.models import Profile


class Post(models.Model):
    profile = models.ForeignKey(
        Profile,
        related_name="posts",
        on_delete=models.CASCADE
    )
    user_likes = models.ManyToManyField(
        Profile,
        related_name='posts_likes',
        blank=True)
    link = models.URLField()
    created = models.DateField(
        auto_now_add=True,
        db_index=True
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"Post created: {self.created}"


class Comment(models.Model):
    author = models.CharField(max_length=255)
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=250)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.body}'


class Action(models.Model):

    profile = models.ForeignKey(Profile,
                             related_name='actions',
                             db_index=True,
                             on_delete=models.CASCADE)
    verb = models.CharField(max_length=255)
    target_ct = models.ForeignKey(ContentType,
                                  blank=True,
                                  null=True,
                                  related_name='target_obj',
                                  on_delete=models.CASCADE)
    target_id = models.PositiveIntegerField(null=True,
                                            blank=True,
                                            db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)
    url = models.URLField(blank=True, null=True)
    comment = models.CharField(max_length=250,
                               blank=True,
                               null=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.profile.username} {self.verb}'

gify/forms.py
from django import forms
from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    """
    Form for creating new entries
    """
    class Meta:
        model = Post
        fields = ("link",)

    def clean_link(self):
        """
        Check if URL links to supported service and transform it
        to embedded version
        """
        link = self.cleaned_data.get("link", "");

        if "you" in link:
            link = self.youtube_embed(link)
        elif "stream" in link:
            link = self.streamable_embed(link)
        else:
            raise forms.ValidationError(("We only accept URLs to YouTube"
                                         " or Streamable"))

        return link

    def youtube_embed(self, url: str) -> str:
        """
        Transform standard youtube URL
        into embedded version
        """
        YOUTUBE_EMBED_URL = "https://www.youtube.com/embed/"
        link_id = url.split("/")[-1]
        if "?" in link_id:
            link_id = link_id.split("?")[0]

        return YOUTUBE_EMBED_URL + link_id

    def streamable_embed(self, url: str) -> str:
        """
        Transform standard streamable URL
        into embedded version
        """
        STREAMABLE_EMBED_URL = "https://streamable.com/e/"
        link_id = url.split("/")[-1]

        return STREAMABLE_EMBED_URL + link_id


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

gify/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Post, Comment, Action
from .forms import PostCreateForm, CommentForm
from .utils import create_action


@login_required
def index(request):
    """
    GIFy homepage
    """
    posts = Post.objects.all()
    paginator = Paginator(posts, 3)
    page = request.GET.get("page", "")
    try:
        posts = paginator.page(page)
        if request.META["CONTENT_TYPE"] == "application/json":
            return render(
                request,
                "gify/list_ajax.html",
                {"posts": posts}
            )
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        return HttpResponse("")

    return render(request,
                  "gify/home.html",
                  {"section": "index", "posts": posts})

@login_required
def wall(request):
    """
    Handle logic for wall view
    """
    actions = Action.objects.exclude(profile=request.user.profile)
    following_ids = request.user.profile.following.values_list('id', flat=True)

    if following_ids:
        actions = actions.filter(profile_id__in=following_ids)

    actions = actions[:10]
    return render(request,
                  "gify/wall.html",
                  {"section": "wall", "actions": actions})


@login_required
def post_create(request):
    """
    View for handling post creation
    """
    if request.method == "POST":
        # form is sent
        form = PostCreateForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user_profile = request.user.profile
            new_post = form.save(commit=False)
            new_post.profile = user_profile
            new_post.save()
            create_action(user_profile, 'created post', new_post, 
                          url=new_post.link)
            return JsonResponse({
                "status": "ok",
                "link": new_post.link,
                'id': new_post.id
            }, status=201)
        else:
            return JsonResponse({
                "status": "error",
                "errors": form.errors.as_json()
            }, safe=False, status=422)
    else:
        form = PostCreateForm()

    return render(
        request,
        "gify/create.html",
        {"form": form}
    )


def retrieve_comments(request):
    """
    View function to handle Ajax requests for 
    retrieving comments under post
    """
    post_id = request.GET.get('post', 0)
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()

    return render(request,
                  'gify/list_comment_ajax.html',
                  {'comments': comments})


@require_POST
def add_comment(request):
    post_id = request.POST.get('post_id', None)
    post = get_object_or_404(Post, id=post_id)
    comment_form = CommentForm(data=request.POST)
    if comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        new_comment.post = post
        new_comment.author = request.user.username
        new_comment.save()
        create_action(request.user.profile, 'commented on', new_comment,
                      new_comment.body,
                      new_comment.post.link)
        return JsonResponse({'comment': {
            'author': request.user.username,
            'body': new_comment.body,
            'created': new_comment.created
        }}, status=201)
    else:
        errors = comment_form.errors.get_json_data(escape_html=True)
        return JsonResponse(errors, status=422)


@login_required
@require_POST
def like_unlike(request):
    """
    Handle liking / unliking posts AJAX logic
    """
    body_parsed = json.loads(request.body)
    post_id = body_parsed.get('id', None)
    action = body_parsed.get('action', None)
    post = Post.objects.get(id=post_id)

    if post:
        if action == 'like':
            post.user_likes.add(request.user.profile)
        else:
            post.user_likes.remove(request.user.profile)
        return JsonResponse({'status': 'ok'}, status=200)
    return JsonResponse({'status': 'error'}, status=422)

gify/templates/gify/create.html
{% extends "base.html" %}

{% block title %}Add post{% endblock %}

{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}
<div class="title">i
	<h1>Add Post</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Add">
	</form>
</div>
{% endblock %}

gify/templates/gify/home.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}GIFy{% endblock %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<template id="post-template">
	<div class="card post">
	<div class="embed-responsive embed-responsive-16by9">
		<iframe id="iframe-video" src="{{ post.link }}" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
	</div>
	<div class="card-body">
		<div class="post-buttons">
			<button class="comment_button">Comment</button>
			<button class="like_button">Like</button>
		</div>
	</div>
	<div class="add-new-post">
		<div>
			<a href="{% url 'account:profile' request.user.username %}">
			<img class="avatar-new-comment" src="{{ request.user.profile.get_avatar|thumbnail_url:'avatar' }}" alt="Your avatar">
			</a>
		</div>
		<form class="new-comment-form" method="POST">
			<input maxlength="250" class="new-comment-input" type="text" placeholder="Add comment...">
		</form>
	</div>

	<div class="comments-container"> </div>
	</div>
</template>

<template id="comment-template">
	<div class="post-comment">
		<div class="post-author">
			<a href="{% url 'account:profile' request.user.username %}">
			<p class="comment-author"><span class="comment-date"></span></p>
			</a>
		</div>
		<div>
			<p class="comment-body"></p>
		</div>
	</div>
</template>

    {% include './list_ajax.html' %} 
{% endblock %}

{% block domready %}
    const container = document.getElementById("container");
    const csrfToken = Cookies.get("csrftoken");
    const posts = document.querySelectorAll(".post");

    async function fetchPosts(page) {
        let response = await fetch(`/?page=${page}`, {
            method: "GET",
            headers: {
                "X-CSRFToken": csrfToken,
                "Content-Type": "application/json"
            },
            mode: "same-origin"
        });

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        } else {
            return await response.text()
        }
    }

    const enableInfiniteScroll = () => {
        let block_request = false;
        let page = 1;

        container.addEventListener("scroll", event => {
            const { scrollTop, clientHeight, scrollHeight } = container;
            if (scrollTop + clientHeight + 50 >=
                scrollHeight && block_request == false) {
                block_request = true;
                page++;
                fetchPosts(page)
                .then(response => {
                    if (response.length == 0) {
                        block_request = true;
                    } else {
                        container.insertAdjacentHTML('beforeend', response);
                        addEventListenerToComment();
                        block_request = false;
                    }
                })
            }
        })
    };

    enableInfiniteScroll();
{% endblock %}

gify/templates/gify/list_actions.html
{% load thumbnail %}
{% for action in actions %}
{% with profile=action.profile %}
<div class="action">
    <div class="action-header">
        <a href="{% url 'account:profile' profile.user.username %}"><img src="{{ profile.get_avatar.url }}" alt=""></a>
        <p class="card-text">{{ action.profile.username }} {{ action.verb }}
        {% if 'following' in action.verb %}{{ action.target.username }}{% endif %}
        </p>
    </div>
    {% if action.url %}
    <div class="action-video">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe src="{{ action.url }}" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
        </div>
    </div>
    {% endif %}
    {% if action.comment %}
    <p class="action-comment">{{ action.comment }}</p>
    {% endif %}
    <span class="action-date">{{ action.created|timesince }} ago</span>
</div>
{% endwith %}
{% endfor %}

gify/templates/gify/list_ajax.html
{% load thumbnail %}
{% for post in posts %}
<div class="card post" data-id="{{ post.id }}">
<div class="embed-responsive embed-responsive-16by9">
	<iframe src="{{ post.link }}" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe>
</div>
	<div class="card-body">
		<div class="post-buttons">
      {% with user_like=post.user_likes.all user_profile=request.user.profile %}
			<button class="comment_button">Comment</button>
      <button class="like_button {% if user_profile in user_like %}
                    liked{%endif%}"
              data-id="{{ post.id }}"
              data-action="{% if user_profile in user_like %}un
                           {% endif %}like">
        {% if user_profile in user_like %}
          Liked
        {% else %}
          Like
        {% endif %}
      </button>
      {% endwith %}
		</div>
	</div>
	<div class="add-new-post">
		<div>
			<a href="{% url 'account:profile' request.user.username %}">
			<img class="avatar-new-comment" src="{{ request.user.profile.get_avatar|thumbnail_url:'avatar' }}" alt="Your avatar">
			</a>
		</div>
		<form class="new-comment-form" method="POST">
			<input maxlength="250" class="new-comment-input" type="text" placeholder="Add comment...">
		</form>
	</div>
<div class="comments-container"> </div>
</div>
{% endfor %}

gify/templates/gify/list_comment_ajax.html
{% for comment in comments %}
	<div class="post-comment">
		<div class="post-author">
			<a href="{% url 'account:profile' comment.author %}">
			<p class="comment-author">{{ comment.author }} <span class="comment-date">{{ comment.created|date:"F d, Y," }}{{ comment.created|time:" g:i A" }}</span></p>
			</a>
		</div>
			<div>
				<p class="comment-body">{{ comment.body }}</p>
			</div>
	</div>
{% endfor %}

gify/templates/gify/wall.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}The wall{% endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}
    {% include './list_actions.html' %}
{% endblock %}